### ISSUE TITLE
1.2 implementations

### ISSUE THREAD

**Issue by khooroko** [CS2103AUG2017-T17-B1/main#46]
1. Verstatile Sort to sort both by name and by debt, and possibly others in the future.
2. Minimise card info. Only part of name, debt, and tags.
3. Add profile pic
4. [WP] Group by postal code https://www.ura.gov.sg/realEstateIIWeb/resources/misc/list_of_postal_districts.htm
5. Do something about tag colours in infopanel (userprefs.json?)
6. Command to set interest (start by implementing a fixed interest perhaps)
7. Automatic interest calculator
8. Muntiple phone numbers
9. Intuitive add tag
10. NLP to make commands (especially add) more intuitive OR
10a. Use viggy's add style because he's cool
11. Critical list
12. [Jel] Command to pay back/borrow more
13. [Vig] Cleared list
14. Add comma separator to debt
15. Add total debt field

try to finish 4, 6, 11, 12, 13 by 1.2 as there are other features that require these

**Comment by jelneo** [comment]
1. critical list
2. indicate and update amount owed by debtor if he/she pays back or borrows more money
3.  sort (by amt owed not sure if you meant this)
4. auto interest calculator
5. Cleared list with: date cleared, total amount borrowed, total paid, days overdue, times borrowed
6. "overdue list"
7. add tag (improve on current edit command cuz all tags will be deleted)
8. filter by tags
9. whitelist
grabbed from project board. some features here can be merged with some abv since they are similar

**Comment by khooroko** [comment]
add comma separator to debt ($10,000 instead of $10000)

**Comment by jaivigneshvenugopal** [comment]
Update the tasks you all are working on guys so that everyone is aware of what is being worked on.

**Comment by khooroko** [comment]
i'm not starting til sat night or sun so take whatever you all like
